version: '3'
services:
  splunk:
    image: splunk/splunk
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=Apple@1234
      - SPLUNK_ENABLE_LISTEN=9997
    ports:
      - "8001:8000"
  splunkforwarder:
    image: splunk/universalforwarder:6.5.3-monitor
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_FORWARD_SERVER=splunk:9997
      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=Apple@1234
      - SPLUNK_ADD=monitor /logs
    restart: always
    depends_on:
      - splunk
    volumes:
      - /logs/app.json:/logs