# Use root/example as user/password credentials
version: '3.1'

networks:
  rmoff_services:
    name: rmoff_services

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - rmoff_services
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flight-booking

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    networks:
      - rmoff_services
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root